
modLoader="javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId="potionrings2"
version="1.1.2"
displayName="Potion Rings"
authors="gobies"
description='''Infinite potion effects in the form of rings'''
credits="Credits to Vazkii as the original creator of this mod"

[[dependencies.potionrings2]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.potionrings2]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side= "BOTH"

[[dependencies.potionrings2]]
modId="curios"
mandatory=true
versionRange ="[5.2.0+1.20.1,)"
ordering="NONE"
side="BOTH"