
modLoader="javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mods]]
modId="potionrings2"
version="1.1.2"
displayName="Potion Rings"
authors="gobies"
description='''Infinite potion effects in the form of rings'''
credits="Credits to Vazkii as the original creator of this mod"

[[dependencies.potionrings2]]
modId="neoforge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.potionrings2]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side= "BOTH"

[[dependencies.potionrings2]]
modId="curios"
type="required"
versionRange ="[9.5.0+1.20.1,)"
ordering="NONE"
side="BOTH"